[www]

; Utilisateur Linux utilisé par les processus PHP
user = www-data

; Groupe Linux des processus PHP
group = www-data

; Port sur lequel php ecoute
listen = 9000

; (pm= process manager)Choix du mode de gestion des processus PHP (dynamic est le standard)
pm = dynamic

; Nombre MAXIMUM de processus PHP simultanés (max 5 requêtes PHP en parallèle)
pm.max_children = 5

; Nombre de processus créés au démarrage
pm.start_servers = 2

; Nombre MINIMUM de processus inactifs gardés prêts
pm.min_spare_servers = 1

; Nombre MAXIMUM de workers inactifs
pm.max_spare_servers = 3

; Autorise PHP à accéder aux variables d’environnement Docker (pas clear env quoi)
clear_env = no