events {}  #bloc obligatoire pour nginx (vide=config par default)

http {
    server {
        listen 443 ssl;
        server_name tgomez-f.42.fr; #nom de domaine

        ssl_protocols TLSv1.2 TLSv1.3; # dit a nginx d'utiliser seulement ces 2 protocoles
        ssl_prefer_server_ciphers off; # laisse le client choisir les algorithmes de chiffrement(évite certains problèmes de compatibilité TLS)

        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        
        index index.php; # fichier a afficher par default
        root /var/www/wordpress; # la racine du site web


        location / {
             # cette loaction capture toutes les URLS /
            try_files $uri $uri/ /index.php?$args; # teste le fichier directement ou si cest un dossier si non il redirige vers index.php
        }

        location ~ \.php$ { # capture toutes les URLS finissant par *.php

            include fastcgi_params; # charge des variables fastcgi pour utiliser la ligne dapres
            fastcgi_pass wordpress:9000; # envoie les fichiers PHP au container wordpress via port 9000
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            # indique a PHP-FPM quel fchier executer
        }
    }
}