events {}  #bloc obligatoire pour nginx (vide=config par default)

http {
    server {
        listen 443 ssl;
        server_name tgomez-f.42.fr;

        ssl_protocols TLSv1.2 TLSv1.3; # dit a nginx d'utiliser seulement ces 2 protocoles
        ssl_prefer_server_ciphers off; # laisse le client choisir les algorithmes de chiffrement(évite certains problèmes de compatibilité TLS)

        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        
        index index.php;
        root /var/www/wordpress;


        location / {
            try_files $uri $uri/ /index.php?$args; # teste les fichiers et dossier, si fail renvoie erreur 404 
        }


        location ~ \.php$ { # / = racine du site    
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}